import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { FileText, ShieldAlert, CheckCircle, Scale } from "lucide-react";

export const metadata: Metadata = {
  title: "Terms of Service | TagGeneratorPro",
  description:
    "Review the Terms of Service for using TagGeneratorPro (taggeneratorpro.online). Free terms, acceptable use, and content disclaimers for social media creators.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50 dark:bg-[#090d16] text-slate-900 dark:text-slate-100 transition-colors">
      <Navbar />

      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 py-10 w-full space-y-8">
        {/* Header */}
        <div className="space-y-3 text-center sm:text-left">
          <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-100 dark:bg-indigo-950/60 text-indigo-700 dark:text-indigo-300 border border-indigo-300/40">
            <Scale className="w-3.5 h-3.5" />
            <span>TERMS & CONDITIONS</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
            Terms of Service
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400">
            Last Updated: September 17, 2026 • Effective Date: January 1, 2026
          </p>
        </div>

        {/* Content Body */}
        <div className="p-6 sm:p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs space-y-8 text-xs sm:text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {/* Section 1 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">1.</span>
              Agreement to Terms
            </h2>
            <p>
              By accessing and using <strong>TagGeneratorPro</strong> (accessible via <strong>taggeneratorpro.online</strong>), you agree to be bound by these Terms of Service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site.
            </p>
          </section>

          {/* Section 2 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">2.</span>
              Free Service & Permitted Use
            </h2>
            <p>
              TagGeneratorPro provides free software utilities to generate keywords, hashtags, video titles, descriptions, and creator profile bios. Permission is granted to temporarily use the materials and generated outputs for personal, educational, and commercial content creation purposes.
            </p>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1.5 text-slate-600 dark:text-slate-400">
              <li>Use the website in any manner that could disable, overburden, or impair our servers.</li>
              <li>Deploy automated scripts, scrapers, or bots that generate abusive query volume.</li>
              <li>Attempt to decompile or reverse engineer any software contained on the website.</li>
              <li>Use generated assets to promote illegal activities, hate speech, harassment, or malicious spam.</li>
            </ul>
          </section>

          {/* Section 3 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">3.</span>
              AI & Algorithmic Output Disclaimer
            </h2>
            <p>
              The tags, titles, descriptions, and bios generated by TagGeneratorPro are produced via heuristic algorithmic databases and artificial intelligence algorithms. While we strive for maximum accuracy, search volume relevance, and character compliance (e.g., YouTube 500-character limits), all suggestions are provided <strong>&ldquo;as is&rdquo;</strong> without warranties of guaranteed search rankings or reach.
            </p>
            <p>
              You retain full discretion and responsibility for reviewing, vetting, and editing any generated content prior to publishing it on your social media channels.
            </p>
          </section>

          {/* Section 4 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">4.</span>
              Third-Party Platform Trademarks & Policies
            </h2>
            <p>
              YouTube, Instagram, TikTok, Facebook, and their respective logos are registered trademarks of their corresponding parent corporations (Google LLC, Meta Platforms, Inc., ByteDance Ltd.). TagGeneratorPro is an independent third-party tool and is not endorsed by, directly affiliated with, maintained, or sponsored by any of these platforms.
            </p>
            <p>
              Users are strictly responsible for abiding by the Community Guidelines and Terms of Service of each social media network when publishing content.
            </p>
          </section>

          {/* Section 5 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">5.</span>
              Limitation of Liability
            </h2>
            <p>
              In no event shall TagGeneratorPro or its suppliers be liable for any damages (including, without limitation, damages for loss of data, loss of audience, account suspension on external platforms, or business interruption) arising out of the use or inability to use the tools on TagGeneratorPro.
            </p>
          </section>

          {/* Section 6 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">6.</span>
              Modifications to Service & Terms
            </h2>
            <p>
              TagGeneratorPro may revise these Terms of Service for its website at any time without prior notice. By using this website, you agree to be bound by the current version of these Terms of Service.
            </p>
          </section>

          {/* Section 7 */}
          <section className="space-y-3">
            <h2 className="text-lg font-bold text-slate-900 dark:text-white flex items-center gap-2">
              <span className="text-indigo-500 font-mono text-sm">7.</span>
              Contact Information
            </h2>
            <p>
              If you have any questions regarding these Terms of Service, you may contact our legal & operations desk:
            </p>
            <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 font-mono text-xs">
              Email: support@taggeneratorpro.online<br />
              Website: https://taggeneratorpro.online
            </div>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
